apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eurserservice.name }}
  labels:
    app: containerPort
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.eurserservice.containerPort }}
  selector:
    app: {{ .Values.eurserservice.deploymentName }}